// src/app/admin/page.tsx
'use client'

import { motion } from 'framer-motion'
import { BarChart3, TrendingUp, Users, AlertCircle, CheckCircle, Clock, Activity, Database, Shield, FileText } from 'lucide-react'
import StaffGuard from '../../components/StaffGuard'
import { usePatientStore } from '../../lib/store/patientStore'
import { computeAdminSummary } from '../../lib/utils/adminSummary'
import { MEDIAN_TOTAL_STAY_MINUTES, MEDIAN_TO_PHYSICIAN_MINUTES, MCM_MASTER_MEDIAN_TIME_TO_PHYSICIAN_MINUTES } from '../../lib/model/modelConstants'
import { Sidebar } from '../../components/ui/sidebar'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/table'
import { Skeleton } from '../../components/ui/skeleton'
import { cn } from '@/lib/utils/cn'

export default function AdminDashboardPage() {
  const patients = usePatientStore((state) => state.patients)
  const summary = computeAdminSummary(patients)
  
  const flagLabels: Record<string, { label: string; icon: string }> = {
    mobility: { label: 'Mobility Impairment', icon: '🦽' },
    chronicPain: { label: 'Chronic Pain', icon: '💊' },
    sensory: { label: 'Sensory Sensitivity', icon: '🔊' },
    cognitive: { label: 'Cognitive Overload', icon: '🧠' },
    language: { label: 'Language Barrier', icon: '🌐' },
    alone: { label: 'No Support Person', icon: '👤' },
  }
  
  const getBurdenStatus = (burden: number) => {
    if (burden >= 70) return { label: 'High strain', color: 'text-red-600', bg: 'bg-red-500/10', border: 'border-red-500/30' }
    if (burden >= 30) return { label: 'Normal range', color: 'text-primary', bg: 'bg-primary/10', border: 'border-primary/30' }
    return { label: 'Low burden', color: 'text-green-600', bg: 'bg-green-500/10', border: 'border-green-500/30' }
  }
  
  const burdenStatus = getBurdenStatus(summary.averageBurden)
  
  const sidebarItems = [
    { id: 'overview', label: 'Overview', icon: <BarChart3 className="h-4 w-4" /> },
    { id: 'equity', label: 'Equity Analysis', icon: <Users className="h-4 w-4" /> },
    { id: 'model', label: 'Model Health', icon: <Activity className="h-4 w-4" /> },
    { id: 'anchors', label: 'Model Anchors', icon: <Database className="h-4 w-4" /> },
  ]
  
  const StatCard = ({ title, value, subtitle, icon: Icon, trend, className }: {
    title: string
    value: string | number
    subtitle?: string
    icon: React.ElementType
    trend?: { value: number; label: string }
    className?: string
  }) => (
    <Card className={cn("hover:shadow-lg transition-shadow", className)}>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium text-muted-foreground">
          {title}
        </CardTitle>
        <Icon className="h-4 w-4 text-muted-foreground" />
      </CardHeader>
      <CardContent>
        <div className="text-2xl font-bold text-foreground">{value}</div>
        {subtitle && (
          <p className="text-xs text-muted-foreground mt-1">{subtitle}</p>
        )}
        {trend && (
          <div className="flex items-center pt-1">
            <span className={cn(
              "text-xs font-medium",
              trend.value > 0 ? "text-red-600" : "text-green-600"
            )}>
              {trend.value > 0 ? '+' : ''}{trend.value}%
            </span>
            <span className="text-xs text-muted-foreground ml-1">{trend.label}</span>
          </div>
        )}
      </CardContent>
    </Card>
  )
  
  return (
    <StaffGuard>
      <div className="min-h-screen bg-background flex">
        {/* Sidebar */}
        <Sidebar
          items={sidebarItems}
          activeItem="overview"
          onItemClick={(id) => console.log('Navigate to:', id)}
        />
        
        {/* Main Content */}
        <div className="flex-1 flex flex-col">
          {/* Header */}
          <motion.header
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="sticky top-16 z-40 border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60"
          >
            <div className="px-8 py-6">
              <div className="flex items-center justify-between">
                <div>
                  <h1 className="text-3xl font-bold text-foreground flex items-center">
                    <BarChart3 className="h-8 w-8 mr-3 text-primary" />
                    Admin Dashboard
                  </h1>
                  <p className="text-sm text-muted-foreground mt-1">
                    Model Health & Equity Overview (Read-Only)
                  </p>
                </div>
                <div className="flex items-center space-x-2 px-3 py-1.5 rounded-lg bg-muted border border-border">
                  <Shield className="h-4 w-4 text-muted-foreground" />
                  <span className="text-xs text-muted-foreground">Read-Only Mode</span>
                </div>
              </div>
            </div>
          </motion.header>
          
          <div className="flex-1 px-8 py-6 overflow-auto">
            {/* Model Health Section */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="mb-8"
            >
              <div className="mb-6">
                <h2 className="text-2xl font-bold text-foreground mb-2 flex items-center">
                  <Activity className="h-6 w-6 mr-3 text-primary" />
                  Model Health
                </h2>
                <p className="text-sm text-muted-foreground">
                  Real-time metrics and alert distribution
                </p>
              </div>
              
              <div className="grid gap-4 md:grid-cols-3 mb-6">
                <StatCard
                  title="Total Patients"
                  value={summary.alertDistribution.total}
                  subtitle="Active in system"
                  icon={Users}
                />
                <StatCard
                  title="Average Burden"
                  value={summary.averageBurden.toFixed(1)}
                  subtitle={burdenStatus.label}
                  icon={TrendingUp}
                  className={cn(burdenStatus.bg, burdenStatus.border)}
                />
                <StatCard
                  title="Missed Check-In Rate"
                  value={`${(summary.missedCheckInRate * 100).toFixed(1)}%`}
                  subtitle="Patients with check-in > 20 min ago"
                  icon={AlertCircle}
                  className="border-amber-500/20 bg-amber-500/5"
                />
              </div>
              
              {/* Alert Distribution Card */}
              <Card>
                <CardHeader>
                  <CardTitle>Alert Distribution</CardTitle>
                  <CardDescription>Current status breakdown across all patients</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="flex items-center justify-between p-4 rounded-lg bg-green-500/10 border border-green-500/20">
                      <div className="flex items-center space-x-3">
                        <CheckCircle className="h-5 w-5 text-green-600" />
                        <span className="font-semibold text-foreground">GREEN</span>
                      </div>
                      <div className="text-right">
                        <div className="text-2xl font-bold text-green-600">
                          {summary.alertDistribution.green}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {summary.alertDistribution.total > 0
                            ? Math.round((summary.alertDistribution.green / summary.alertDistribution.total) * 100)
                            : 0}% of total
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center justify-between p-4 rounded-lg bg-amber-500/10 border border-amber-500/20">
                      <div className="flex items-center space-x-3">
                        <AlertCircle className="h-5 w-5 text-amber-600" />
                        <span className="font-semibold text-foreground">AMBER</span>
                      </div>
                      <div className="text-right">
                        <div className="text-2xl font-bold text-amber-600">
                          {summary.alertDistribution.amber}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {summary.alertDistribution.total > 0
                            ? Math.round((summary.alertDistribution.amber / summary.alertDistribution.total) * 100)
                            : 0}% of total
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center justify-between p-4 rounded-lg bg-red-500/10 border border-red-500/20">
                      <div className="flex items-center space-x-3">
                        <AlertCircle className="h-5 w-5 text-red-600" />
                        <span className="font-semibold text-foreground">RED</span>
                      </div>
                      <div className="text-right">
                        <div className="text-2xl font-bold text-red-600">
                          {summary.alertDistribution.red}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {summary.alertDistribution.total > 0
                            ? Math.round((summary.alertDistribution.red / summary.alertDistribution.total) * 100)
                            : 0}% of total
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.section>
            
            {/* Equity Overview Section */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="mb-8"
            >
              <div className="mb-6">
                <h2 className="text-2xl font-bold text-foreground mb-2 flex items-center">
                  <Users className="h-6 w-6 mr-3 text-primary" />
                  Equity Overview
                </h2>
                <p className="text-sm text-muted-foreground">
                  Average burden and % RED by accessibility flag
                </p>
              </div>
              
              <Card>
                <CardHeader>
                  <CardTitle>Accessibility Flags Analysis</CardTitle>
                  <CardDescription>Impact of accessibility needs on patient burden</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {Object.entries(flagLabels).map(([key, { label, icon }]) => {
                      const equityData = summary.equityByFlag[key as keyof typeof summary.equityByFlag]
                      const count = patients.filter(p => p.accessibilityProfile[key as keyof typeof p.accessibilityProfile]).length
                      const percentage = summary.alertDistribution.total > 0
                        ? Math.round((count / summary.alertDistribution.total) * 100)
                        : 0
                      
                      return (
                        <motion.div
                          key={key}
                          whileHover={{ scale: 1.02 }}
                          className="bg-muted/50 rounded-lg p-4 border border-border"
                        >
                          <div className="flex items-center justify-between mb-3">
                            <div className="flex items-center space-x-2">
                              <span className="text-2xl">{icon}</span>
                              <span className="text-sm font-medium text-foreground">{label}</span>
                            </div>
                            <div className="text-right">
                              <div className="text-lg font-bold text-foreground">{count}</div>
                              <div className="text-xs text-muted-foreground">{percentage}%</div>
                            </div>
                          </div>
                          {equityData && (
                            <div className="pt-3 border-t border-border space-y-2">
                              <div className="flex items-center justify-between text-xs">
                                <span className="text-muted-foreground">Avg Burden:</span>
                                <span className="font-semibold text-foreground">{equityData.avgBurden}</span>
                              </div>
                              <div className="flex items-center justify-between text-xs">
                                <span className="text-muted-foreground">% RED:</span>
                                <span className="font-semibold text-red-600">{equityData.redPercent.toFixed(1)}%</span>
                              </div>
                            </div>
                          )}
                        </motion.div>
                      )
                    })}
                  </div>
                </CardContent>
              </Card>
            </motion.section>
            
            {/* Model Anchors Section */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
            >
              <div className="mb-6">
                <h2 className="text-2xl font-bold text-foreground mb-2 flex items-center">
                  <Database className="h-6 w-6 mr-3 text-primary" />
                  Model Anchors
                </h2>
                <p className="text-sm text-muted-foreground">
                  Reference values from research studies
                </p>
              </div>
              
              <Card>
                <CardHeader>
                  <CardTitle>Research-Based Constants</CardTitle>
                  <CardDescription>Median wait times and model parameters</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="bg-muted/50 rounded-lg p-6 border border-border">
                      <div className="flex items-center space-x-2 mb-3">
                        <FileText className="h-5 w-5 text-primary" />
                        <div className="text-sm font-bold text-foreground">CIHI Study</div>
                      </div>
                      <div className="space-y-2">
                        <div className="flex justify-between text-sm">
                          <span className="text-muted-foreground">Total Stay:</span>
                          <span className="font-bold text-foreground">{MEDIAN_TOTAL_STAY_MINUTES}m</span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-muted-foreground">To Physician:</span>
                          <span className="font-bold text-foreground">{MEDIAN_TO_PHYSICIAN_MINUTES}m</span>
                        </div>
                      </div>
                    </div>
                    <div className="bg-muted/50 rounded-lg p-6 border border-border">
                      <div className="flex items-center space-x-2 mb-3">
                        <FileText className="h-5 w-5 text-primary" />
                        <div className="text-sm font-bold text-foreground">McMaster Study</div>
                      </div>
                      <div className="space-y-2">
                        <div className="flex justify-between text-sm">
                          <span className="text-muted-foreground">Time to Physician:</span>
                          <span className="font-bold text-foreground">{MCM_MASTER_MEDIAN_TIME_TO_PHYSICIAN_MINUTES}m</span>
                        </div>
                      </div>
                    </div>
                    <div className="bg-muted/50 rounded-lg p-6 border border-border">
                      <div className="flex items-center space-x-2 mb-3">
                        <Shield className="h-5 w-5 text-primary" />
                        <div className="text-sm font-bold text-foreground">Data Sources</div>
                      </div>
                      <div className="space-y-2 text-xs text-muted-foreground">
                        <div>• Health Quality Council of Alberta (HQCA)</div>
                        <div>• Statistics Canada – Disability in Canada (2024)</div>
                      </div>
                    </div>
                  </div>
                  
                  <div className="mt-6 pt-6 border-t border-border">
                    <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-4">
                      <p className="text-sm text-foreground font-semibold flex items-center">
                        <Shield className="h-4 w-4 mr-2 text-amber-600" />
                        <strong>Safety:</strong> Admin cannot change thresholds, weights, patients, LWBS scaling, or triage.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.section>
          </div>
        </div>
      </div>
    </StaffGuard>
  )
}

// frontend/src/app/features/admin/admin.component.ts
import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { AsyncPipe, DecimalPipe } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatChipModule } from '@angular/material/chip';
import { MatIconModule } from '@angular/material/icon';
import { MatTableModule } from '@angular/material/table';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatTooltipModule } from '@angular/material/tooltip';
import { AuthService } from '../../core/auth/auth.service';
import { AdminSummaryService, type AdminSummary, type EquityFlagKey } from '../../core/services/admin-summary.service';
import {
  MEDIAN_TOTAL_STAY_MINUTES,
  MEDIAN_TO_PHYSICIAN_MINUTES,
  MCM_MASTER_MEDIAN_TIME_TO_PHYSICIAN_MINUTES,
} from '../../../lib/model/modelConstants';
import { DashboardLayoutComponent, NavItem } from '../../components/layout/dashboard-layout.component';
import { SkeletonLoaderComponent } from '../../components/skeleton-loader/skeleton-loader.component';

const EQUITY_LABELS: Record<EquityFlagKey, string> = {
  mobility: 'Mobility',
  chronicPain: 'Chronic pain',
  sensory: 'Sensory',
  cognitive: 'Cognitive',
  language: 'Language',
  alone: 'Alone',
};

@Component({
  selector: 'app-admin',
  standalone: true,
  imports: [
    AsyncPipe,
    DecimalPipe,
    MatCardModule,
    MatChipModule,
    MatIconModule,
    MatTableModule,
    MatProgressBarModule,
    MatTooltipModule,
    DashboardLayoutComponent,
    SkeletonLoaderComponent,
  ],
  template: `
    <app-dashboard-layout
      [navItems]="navItems"
      [breadcrumbs]="['Dashboard', 'Admin']"
      [notificationCount]="0"
      (onSignOut)="signOut()"
    >
      <div class="admin-dashboard max-width-container">
        <!-- Page Header -->
        <div class="page-header">
          <div class="header-content">
            <div>
              <h1>Admin Dashboard</h1>
              <p class="subtitle">Read-only — Model health & equity overview</p>
            </div>
            <mat-chip class="read-only-chip" color="accent">
              <mat-icon matChipAvatar>lock</mat-icon>
              Read-Only Mode
            </mat-chip>
          </div>
        </div>

        @if (summary$ | async; as s) {
          <!-- Model Health Section -->
          <mat-card class="section-card">
            <mat-card-header>
              <mat-card-title>
                <mat-icon>analytics</mat-icon>
                Model Health
              </mat-card-title>
              <mat-card-subtitle>Real-time metrics and alert distribution</mat-card-subtitle>
            </mat-card-header>
            <mat-card-content>
              <div class="model-health-grid">
                <!-- Alert Distribution -->
                <div class="alert-distribution">
                  <h3>Alert Distribution</h3>
                  <div class="alert-bars">
                    <div class="alert-bar-item">
                      <div class="bar-header">
                        <span class="bar-label">Green</span>
                        <span class="bar-value">{{ s.alertDistribution.greenPercent | number:'1.0-1' }}%</span>
                      </div>
                      <mat-progress-bar
                        mode="determinate"
                        [value]="s.alertDistribution.greenPercent"
                        color="primary"
                        class="progress-bar"
                      ></mat-progress-bar>
                      <div class="bar-count">{{ s.alertDistribution.green }} patients</div>
                    </div>
                    <div class="alert-bar-item">
                      <div class="bar-header">
                        <span class="bar-label">Amber</span>
                        <span class="bar-value">{{ s.alertDistribution.amberPercent | number:'1.0-1' }}%</span>
                      </div>
                      <mat-progress-bar
                        mode="determinate"
                        [value]="s.alertDistribution.amberPercent"
                        color="accent"
                        class="progress-bar"
                      ></mat-progress-bar>
                      <div class="bar-count">{{ s.alertDistribution.amber }} patients</div>
                    </div>
                    <div class="alert-bar-item">
                      <div class="bar-header">
                        <span class="bar-label">Red</span>
                        <span class="bar-value">{{ s.alertDistribution.redPercent | number:'1.0-1' }}%</span>
                      </div>
                      <mat-progress-bar
                        mode="determinate"
                        [value]="s.alertDistribution.redPercent"
                        color="warn"
                        class="progress-bar"
                      ></mat-progress-bar>
                      <div class="bar-count">{{ s.alertDistribution.red }} patients</div>
                    </div>
                  </div>
                </div>

                <!-- Average Burden -->
                <mat-card class="stat-card" [class.normal]="s.avgBurden >= 30 && s.avgBurden <= 55" [class.strain]="s.avgBurden >= 70">
                  <mat-card-content>
                    <div class="stat-content">
                      <div class="stat-icon">
                        <mat-icon>trending_up</mat-icon>
                      </div>
                      <div class="stat-details">
                        <div class="stat-value">{{ s.avgBurden | number:'1.0-1' }}</div>
                        <div class="stat-label">Average Burden</div>
                        <div class="stat-hint">30–55 normal · 70+ sustained strain</div>
                      </div>
                    </div>
                  </mat-card-content>
                </mat-card>

                <!-- Missed Check-In Rate -->
                <mat-card class="stat-card warning">
                  <mat-card-content>
                    <div class="stat-content">
                      <div class="stat-icon warning">
                        <mat-icon>schedule</mat-icon>
                      </div>
                      <div class="stat-details">
                        <div class="stat-value">{{ s.missedCheckInRate | number:'1.0-1' }}%</div>
                        <div class="stat-label">Missed Check-In Rate</div>
                        <div class="stat-hint">Engagement health</div>
                      </div>
                    </div>
                  </mat-card-content>
                </mat-card>
              </div>
            </mat-card-content>
          </mat-card>

          <!-- Equity Overview Section -->
          <mat-card class="section-card">
            <mat-card-header>
              <mat-card-title>
                <mat-icon>balance</mat-icon>
                Equity Overview
              </mat-card-title>
              <mat-card-subtitle>Average burden and % RED by accessibility flag</mat-card-subtitle>
            </mat-card-header>
            <mat-card-content>
              <div class="equity-grid">
                <!-- Average Burden by Flag -->
                <div class="equity-chart">
                  <h3>Average Burden by Flag</h3>
                  <div class="equity-bars">
                    @for (key of equityKeys; track key) {
                      <div class="equity-bar-item">
                        <div class="bar-header">
                          <span class="bar-label">{{ EQUITY_LABELS[key] }}</span>
                          <span class="bar-value">{{ s.avgBurdenByFlag[key] | number:'1.0-1' }}</span>
                        </div>
                        <mat-progress-bar
                          mode="determinate"
                          [value]="s.avgBurdenByFlag[key]"
                          class="progress-bar neutral"
                        ></mat-progress-bar>
                      </div>
                    }
                  </div>
                </div>

                <!-- % Red by Flag -->
                <div class="equity-chart">
                  <h3>% Red by Flag</h3>
                  <div class="equity-bars">
                    @for (key of equityKeys; track key) {
                      <div class="equity-bar-item">
                        <div class="bar-header">
                          <span class="bar-label">{{ EQUITY_LABELS[key] }}</span>
                          <span class="bar-value">{{ s.redRateByFlag[key] | number:'1.0-1' }}%</span>
                        </div>
                        <mat-progress-bar
                          mode="determinate"
                          [value]="s.redRateByFlag[key]"
                          color="warn"
                          class="progress-bar"
                        ></mat-progress-bar>
                      </div>
                    }
                  </div>
                </div>
              </div>
            </mat-card-content>
          </mat-card>

          <!-- Model Anchors Section -->
          <mat-card class="section-card">
            <mat-card-header>
              <mat-card-title>
                <mat-icon>book</mat-icon>
                Model Anchors & Sources
              </mat-card-title>
              <mat-card-subtitle>Reference values from research studies</mat-card-subtitle>
            </mat-card-header>
            <mat-card-content>
              <div class="anchors-grid">
                <div class="anchor-item">
                  <mat-icon class="anchor-icon">science</mat-icon>
                  <div class="anchor-content">
                    <h4>CIHI Medians</h4>
                    <ul>
                      <li>Total stay: <strong>{{ MEDIAN_TOTAL_STAY_MINUTES }} min</strong></li>
                      <li>Time to physician: <strong>{{ MEDIAN_TO_PHYSICIAN_MINUTES }} min</strong></li>
                    </ul>
                  </div>
                </div>
                <div class="anchor-item">
                  <mat-icon class="anchor-icon">school</mat-icon>
                  <div class="anchor-content">
                    <h4>McMaster Study</h4>
                    <ul>
                      <li>Early risk threshold: <strong>{{ MCM_MASTER_MEDIAN_TIME_TO_PHYSICIAN_MINUTES }} min</strong></li>
                    </ul>
                  </div>
                </div>
                <div class="anchor-item">
                  <mat-icon class="anchor-icon">local_hospital</mat-icon>
                  <div class="anchor-content">
                    <h4>LWBS Source</h4>
                    <ul>
                      <li>Health Quality Council of Alberta (HQCA)</li>
                    </ul>
                  </div>
                </div>
                <div class="anchor-item">
                  <mat-icon class="anchor-icon">bar_chart</mat-icon>
                  <div class="anchor-content">
                    <h4>Weights Source</h4>
                    <ul>
                      <li>Statistics Canada – Disability in Canada (2024)</li>
                    </ul>
                  </div>
                </div>
              </div>

              <div class="safety-notice">
                <mat-icon>security</mat-icon>
                <div>
                  <strong>Safety:</strong> Admin cannot change thresholds, weights, patients, LWBS scaling, or triage.
                </div>
              </div>
            </mat-card-content>
          </mat-card>
        } @else {
          <app-skeleton-loader type="card" [rows]="3"></app-skeleton-loader>
        }
      </div>
    </app-dashboard-layout>
  `,
  styles: [`
    .admin-dashboard {
      padding: 24px;
    }

    .page-header {
      margin-bottom: 32px;
    }

    .header-content {
      display: flex;
      justify-content: space-between;
      align-items: center;
      flex-wrap: wrap;
      gap: 16px;
    }

    .page-header h1 {
      font-size: 24px;
      font-weight: 600;
      color: #1A1A2E;
      margin: 0 0 8px;
    }

    .subtitle {
      font-size: 14px;
      color: #666;
      margin: 0;
    }

    .read-only-chip {
      font-weight: 500;
    }

    .section-card {
      margin-bottom: 24px;
    }

    .section-card mat-card-title {
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 16px;
      font-weight: 600;
    }

    .section-card mat-icon {
      color: #1E3A5F;
    }

    .model-health-grid {
      display: grid;
      grid-template-columns: 2fr 1fr 1fr;
      gap: 24px;
      margin-top: 16px;
    }

    @media (max-width: 1024px) {
      .model-health-grid {
        grid-template-columns: 1fr;
      }
    }

    .alert-distribution {
      flex: 1;
    }

    .alert-distribution h3 {
      font-size: 14px;
      font-weight: 600;
      color: #1A1A2E;
      margin: 0 0 16px;
    }

    .alert-bars {
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    .alert-bar-item {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .bar-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .bar-label {
      font-size: 14px;
      font-weight: 500;
      color: #1A1A2E;
    }

    .bar-value {
      font-size: 14px;
      font-weight: 600;
      color: #1A1A2E;
    }

    .progress-bar {
      height: 8px;
      border-radius: 4px;
    }

    .progress-bar.neutral {
      ::ng-deep .mdc-linear-progress__buffer {
        background-color: #E0E0E0;
      }
      ::ng-deep .mdc-linear-progress__bar-inner {
        background-color: #1E3A5F;
      }
    }

    .bar-count {
      font-size: 12px;
      color: #666;
    }

    .stat-card {
      border-left: 4px solid #1E3A5F;
    }

    .stat-card.normal {
      border-left-color: #2e7d32;
    }

    .stat-card.strain {
      border-left-color: #d32f2f;
    }

    .stat-card.warning {
      border-left-color: #f57c00;
    }

    .stat-content {
      display: flex;
      align-items: center;
      gap: 16px;
    }

    .stat-icon {
      width: 48px;
      height: 48px;
      border-radius: 8px;
      display: flex;
      align-items: center;
      justify-content: center;
      background: #F4F6F9;

      mat-icon {
        color: #1E3A5F;
        font-size: 24px;
      }

      &.warning mat-icon {
        color: #f57c00;
      }
    }

    .stat-details {
      flex: 1;
    }

    .stat-value {
      font-size: 28px;
      font-weight: 700;
      color: #1A1A2E;
      line-height: 1;
      margin-bottom: 4px;
    }

    .stat-label {
      font-size: 14px;
      color: #666;
      margin-bottom: 4px;
    }

    .stat-hint {
      font-size: 12px;
      color: #999;
    }

    .equity-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 32px;
      margin-top: 16px;
    }

    @media (max-width: 768px) {
      .equity-grid {
        grid-template-columns: 1fr;
      }
    }

    .equity-chart h3 {
      font-size: 14px;
      font-weight: 600;
      color: #1A1A2E;
      margin: 0 0 16px;
    }

    .equity-bars {
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    .equity-bar-item {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .anchors-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 16px;
      margin-top: 16px;
    }

    .anchor-item {
      display: flex;
      gap: 16px;
      padding: 16px;
      background: #F4F6F9;
      border-radius: 8px;
      border-left: 3px solid #1E3A5F;
    }

    .anchor-icon {
      color: #1E3A5F;
      font-size: 32px;
      width: 32px;
      height: 32px;
    }

    .anchor-content h4 {
      font-size: 14px;
      font-weight: 600;
      color: #1A1A2E;
      margin: 0 0 8px;
    }

    .anchor-content ul {
      margin: 0;
      padding-left: 20px;
      font-size: 13px;
      color: #666;
    }

    .anchor-content li {
      margin-bottom: 4px;
    }

    .safety-notice {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 16px;
      background: #FFF3E0;
      border-left: 4px solid #f57c00;
      border-radius: 4px;
      margin-top: 24px;
      font-size: 13px;
      color: #E65100;

      mat-icon {
        color: #f57c00;
      }
    }
  `],
})
export class AdminComponent {
  private auth = inject(AuthService);
  private router = inject(Router);
  private adminSummary = inject(AdminSummaryService);

  readonly summary$ = this.adminSummary.getSummary$();
  readonly EQUITY_LABELS = EQUITY_LABELS;
  readonly equityKeys: EquityFlagKey[] = ['mobility', 'chronicPain', 'sensory', 'cognitive', 'language', 'alone'];
  readonly MEDIAN_TOTAL_STAY_MINUTES = MEDIAN_TOTAL_STAY_MINUTES;
  readonly MEDIAN_TO_PHYSICIAN_MINUTES = MEDIAN_TO_PHYSICIAN_MINUTES;
  readonly MCM_MASTER_MEDIAN_TIME_TO_PHYSICIAN_MINUTES = MCM_MASTER_MEDIAN_TIME_TO_PHYSICIAN_MINUTES;

  navItems: NavItem[] = [
    { label: 'Staff Dashboard', icon: 'dashboard', route: '/staff' },
    { label: 'Admin Dashboard', icon: 'admin_panel_settings', route: '/admin' },
  ];

  signOut(): void {
    this.auth.clear();
    this.router.navigate(['/']);
  }
}
